/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SourceCode.DataEntry;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mizter Lee
 */
public class InsuranceTab extends javax.swing.JFrame {

    public static void main(String[] args){
        new InsuranceTab();    
    }
    /**
     * Creates new form DataEntryForm
     */
    private DefaultTableModel model;
    private Statement st;
    private ResultSet rs;
    String sql="select * from Insurance";
    public InsuranceTab() {
        initComponents();
        String driver="com.microsoft.sqlserver.jdbc.SQLServerDriver";
        String url="jdbc:sqlserver://localhost:1433;" +
                "databaseName=HealthCareService;user=sa;password=b@nlyonly;";
        try{
            Class.forName(driver);
            Connection con=DriverManager.getConnection(url);
            st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            model=(DefaultTableModel) tbInsurance.getModel();
            
        }catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InsuranceTab.class.getName()).log(Level.SEVERE, null, ex);
        }
        refreshData();
        controlFormLoad();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPerson = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInsurance = new javax.swing.JTable();
        btnInNew = new javax.swing.JButton();
        btnInSave = new javax.swing.JButton();
        btnInEdit = new javax.swing.JButton();
        btnInDelete = new javax.swing.JButton();
        btnInCancel = new javax.swing.JButton();
        btnInClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(18, 55, 92));

        jTabbedPane1.setBackground(new java.awt.Color(18, 55, 92));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("ID:");

        jLabel3.setText("Name:");

        jLabel4.setText("Address:");

        jLabel5.setText("Contact person:");

        jLabel6.setText("Contact:");

        tbInsurance.setBackground(new java.awt.Color(57, 109, 160));
        tbInsurance.setForeground(new java.awt.Color(255, 255, 51));
        tbInsurance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address"
            }
        ));
        jScrollPane1.setViewportView(tbInsurance);

        btnInNew.setBackground(new java.awt.Color(102, 204, 255));
        btnInNew.setText("New");
        btnInNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInNewActionPerformed(evt);
            }
        });

        btnInSave.setBackground(new java.awt.Color(102, 204, 255));
        btnInSave.setText("Save");
        btnInSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInSaveActionPerformed(evt);
            }
        });

        btnInEdit.setBackground(new java.awt.Color(102, 204, 255));
        btnInEdit.setText("Edit");
        btnInEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInEditActionPerformed(evt);
            }
        });

        btnInDelete.setBackground(new java.awt.Color(102, 204, 255));
        btnInDelete.setText("Delete");
        btnInDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInDeleteActionPerformed(evt);
            }
        });

        btnInCancel.setBackground(new java.awt.Color(102, 204, 255));
        btnInCancel.setText("Cancel");
        btnInCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInCancelActionPerformed(evt);
            }
        });

        btnInClose.setBackground(new java.awt.Color(102, 204, 255));
        btnInClose.setText("Close");
        btnInClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txtID)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(35, 35, 35)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(txtPerson, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContact, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnInNew)
                .addGap(35, 35, 35)
                .addComponent(btnInSave)
                .addGap(35, 35, 35)
                .addComponent(btnInEdit)
                .addGap(35, 35, 35)
                .addComponent(btnInDelete)
                .addGap(35, 35, 35)
                .addComponent(btnInCancel)
                .addGap(35, 35, 35)
                .addComponent(btnInClose)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInNew, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInSave, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInCancel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInClose, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insurance Company", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnInCloseActionPerformed

    private void btnInCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInCancelActionPerformed
        // TODO add your handling code here:
        controlFormLoad();
    }//GEN-LAST:event_btnInCancelActionPerformed

    private void btnInDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInDeleteActionPerformed
        // TODO add your handling code here:
        int i=tbInsurance.getSelectedRow();
        model.removeRow(i);
        boolean d=false;
        try{
            rs.absolute(i+1);
            rs.deleteRow();
            d=rs.rowDeleted();

        }catch(Exception ex){
            Logger.getLogger(InsuranceTab.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null,"Deleted= "+d);
        refreshData();
    }//GEN-LAST:event_btnInDeleteActionPerformed

    private void btnInEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInEditActionPerformed
        // TODO add your handling code here:
        txtID.setEditable(false);
        btnInSave.setText("Update");
        btnInNew.setEnabled(false);
        btnInDelete.setEnabled(false);
        int index=tbInsurance.getSelectedRow();
        try{
            rs.absolute(index+1);
            String id=rs.getString("ID");
            String name=rs.getString("Name");
            String add=rs.getString("Addresss");
            txtID.setText(id);
            txtName.setText(name);
            txtAddress.setText(add);
        }catch(Exception ex){
            Logger.getLogger(InsuranceTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInEditActionPerformed

    private void btnInSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInSaveActionPerformed
        if(btnInSave.getText().equalsIgnoreCase("Save")){
            try {
                // TODO add your handling code here:
                String id=txtID.getText();
                String name=txtName.getText();
                String add=txtAddress.getText();
                rs.moveToInsertRow();
                rs.updateString("ID", id);
                rs.updateString("Name",name);
                rs.updateString("Addresss",add);
                rs.insertRow();
                insertRowToTable(id,name,add);
            } catch (SQLException ex) {
                Logger.getLogger(InsuranceTab.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(btnInSave.getText().equalsIgnoreCase("Update")){
            int index=tbInsurance.getSelectedRow();
            String name=txtName.getText();
            String add=txtAddress.getText();
            try{
                rs.absolute(index+1);
                rs.updateString("Name", name);
                rs.updateString("Addresss", add);
                rs.updateRow();
                model.setValueAt(name, index, 1);
                model.setValueAt(add,index,2);
            }catch(Exception ex){
                Logger.getLogger(InsuranceTab.class.getName()).log(Level.SEVERE, null, ex);
            }
            btnInSave.setText("Save");

        }
        clearAllTextFields();
    }//GEN-LAST:event_btnInSaveActionPerformed

    private void btnInNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInNewActionPerformed
        // TODO add your handling code here:
        txtID.setFocusable(true);
        txtID.setEditable(true);
        btnInNew.setEnabled(false);
        btnInDelete.setEnabled(false);
    }//GEN-LAST:event_btnInNewActionPerformed

// FUNCTIONS    
    private void refreshData(){
        Object[] o=new Object[3];
        try{
            rs=st.executeQuery(sql);
            while(rs.next()){
                o[0]=rs.getString("ID");
                o[1]=rs.getString("Name");
                o[2]=rs.getString("Addresss");
                model.addRow(o);
            }
        }catch(SQLException ex){
            Logger.getLogger(InsuranceTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void insertRowToTable(Object o1,Object o2,Object o3){
        Object[] n=new Object[3];
        n[0]=o1;n[1]=o2;n[2]=o3;
        model.addRow(n);
    }
    private void controlFormLoad(){
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        enableAllTextFields(false);
        clearAllTextFields();
        btnInNew.setEnabled(true);
        btnInSave.setEnabled(false);
        btnInEdit.setEnabled(true);
        btnInDelete.setEnabled(true);
        btnInCancel.setEnabled(false);
    }
    private void enableAllTextFields(boolean b){
        txtID.setEnabled(b);
        txtName.setEnabled(b);
        txtAddress.setEnabled(b);
    }
    private void clearAllTextFields(){
        txtID.setText(null);
        txtName.setText(null);
        txtAddress.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInCancel;
    private javax.swing.JButton btnInClose;
    private javax.swing.JButton btnInDelete;
    private javax.swing.JButton btnInEdit;
    private javax.swing.JButton btnInNew;
    private javax.swing.JButton btnInSave;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbInsurance;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPerson;
    // End of variables declaration//GEN-END:variables
}
