import java.awt.Color;

/**
 *
 * @author Sathya
 */
public class AddHP extends javax.swing.JFrame {

    /**
     * Creates new form frmAddHP
     */
    private SubFrame sub;
    
    private Color colorForeExited;
    private Color colorBackExited;
    
    public AddHP() {        
        initComponents();
        
        sub = new SubFrame(this.panel_titlebar, this, new Color(0, 160, 174), 1);
        
        colorForeExited = lblClose.getForeground();
        colorBackExited = lblClose.getBackground();
        
        sub.closeButton(lblClose, this, colorBackExited, colorForeExited);
                
        tfID.requestFocus();   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_titlebar = new javax.swing.JPanel();
        lblTitlebar = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        panel_saveHP = new javax.swing.JPanel();
        lblAddHP = new javax.swing.JLabel();
        panel_cancel = new javax.swing.JPanel();
        lblAddHP1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Healthcare Provider Information");
        setUndecorated(true);
        setResizable(false);

        panel_titlebar.setBackground(new java.awt.Color(0, 160, 174));
        panel_titlebar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_titlebar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblTitlebar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitlebar.setForeground(new java.awt.Color(255, 255, 255));
        lblTitlebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Add_New_25px_1.png"))); // NOI18N
        lblTitlebar.setText("Add - Healthcare Provider");

        lblClose.setBackground(new java.awt.Color(0, 160, 174));
        lblClose.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setOpaque(true);

        javax.swing.GroupLayout panel_titlebarLayout = new javax.swing.GroupLayout(panel_titlebar);
        panel_titlebar.setLayout(panel_titlebarLayout);
        panel_titlebarLayout.setHorizontalGroup(
            panel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titlebarLayout.createSequentialGroup()
                .addComponent(lblTitlebar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_titlebarLayout.setVerticalGroup(
            panel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_titlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTitlebar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jLabel3.setText("Address");

        tfID.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N

        tfName.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N

        tfAddress.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N

        panel_saveHP.setBackground(new java.awt.Color(0, 160, 174));
        panel_saveHP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_saveHP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_saveHP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_saveHPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_saveHPMouseExited(evt);
            }
        });

        lblAddHP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddHP.setForeground(new java.awt.Color(255, 255, 255));
        lblAddHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddHP.setText("Save");

        javax.swing.GroupLayout panel_saveHPLayout = new javax.swing.GroupLayout(panel_saveHP);
        panel_saveHP.setLayout(panel_saveHPLayout);
        panel_saveHPLayout.setHorizontalGroup(
            panel_saveHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddHP, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );
        panel_saveHPLayout.setVerticalGroup(
            panel_saveHPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddHP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_cancel.setBackground(new java.awt.Color(255, 255, 255));
        panel_cancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_cancelMouseExited(evt);
            }
        });

        lblAddHP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddHP1.setForeground(new java.awt.Color(0, 160, 174));
        lblAddHP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddHP1.setText("Cancel");

        javax.swing.GroupLayout panel_cancelLayout = new javax.swing.GroupLayout(panel_cancel);
        panel_cancel.setLayout(panel_cancelLayout);
        panel_cancelLayout.setHorizontalGroup(
            panel_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddHP1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        );
        panel_cancelLayout.setVerticalGroup(
            panel_cancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAddHP1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addComponent(panel_saveHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(panel_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_mainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {panel_cancel, panel_saveHP});

        panel_mainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_saveHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_titlebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_saveHPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_saveHPMouseEntered
        panel_saveHP.setBackground(new Color(77, 201, 212));
    }//GEN-LAST:event_panel_saveHPMouseEntered

    private void panel_saveHPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_saveHPMouseExited
        panel_saveHP.setBackground(new Color(0,160,174));
    }//GEN-LAST:event_panel_saveHPMouseExited

    private void panel_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_cancelMouseClicked
        tfID.setText(null);
        tfName.setText(null);
        tfAddress.setText(null);
        tfID.requestFocus();
    }//GEN-LAST:event_panel_cancelMouseClicked

    private void panel_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_cancelMouseEntered
        panel_cancel.setBackground(Color.lightGray);
    }//GEN-LAST:event_panel_cancelMouseEntered

    private void panel_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_cancelMouseExited
        panel_cancel.setBackground(Color.white);
    }//GEN-LAST:event_panel_cancelMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddHP().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddHP;
    private javax.swing.JLabel lblAddHP1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblTitlebar;
    private javax.swing.JPanel panel_cancel;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_saveHP;
    private javax.swing.JPanel panel_titlebar;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
