/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harry
 */
public class FrmSearchTreatmentMedicine extends javax.swing.JFrame {

    /**
     * Creates new form FrmSearchTreatmentMedicine
     */
    Connection con;
    ResultSet rs,rsMed, rsTreatment;
    String sqlMed, sqlTreatment;
    DefaultTableModel mdlTbMed;
    DefaultTableModel mdlTbTreat;
    
    SubFrame sub;
    
    private Color colorBackExited;
    private Color colorForeExited;  
    
    public FrmSearchTreatmentMedicine() {
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=HealthCareService;user=sa;password=sathya123;");
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        
        SimpleButton();
        
        initComponents();
 
        SetupTable();
        
        colorBackExited = lblClose.getBackground();
        colorForeExited = lblClose.getForeground();
        
        sub = new SubFrame(jPanel1, this, new Color(0, 160, 174), 1);

        sub.closeButton(lblClose, this, colorBackExited, colorForeExited);
//        DecoratedForm();
        
        ConfigControl();
        
        GetDisease();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbDisease = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTreatment = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMedicine = new javax.swing.JTable();
        lblClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setUndecorated(true);

        cmbDisease.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        cmbDisease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Disease" }));
        cmbDisease.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDiseaseItemStateChanged(evt);
            }
        });

        tbTreatment.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tbTreatment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Treatment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbTreatment);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Treatment");

        tbMedicine.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tbMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbMedicine);

        lblClose.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Disease");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Medicine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDisease, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(446, 446, 446))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDiseaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDiseaseItemStateChanged
        // TODO add your handling code here:
        mdlTbMed.setRowCount(0);
        mdlTbTreat.setRowCount(0);
        try {
            // TODO add your handling code here:
            ResultSetMetaData rsmdmed, rsmdtrt;
            InitQuery();
            rsMed = con.createStatement().executeQuery(sqlMed);
            rsTreatment = con.createStatement().executeQuery(sqlTreatment);
            rsmdmed = rsMed.getMetaData();
            rsmdtrt = rsTreatment.getMetaData();
            while(rsMed.next())
            {
                Vector<String> lst = new Vector<String>();
                lst.add(rsMed.getString(rsmdmed.getColumnName(2)));
                mdlTbMed.addRow(lst);
            }
            while(rsTreatment.next())
            {
                Vector<String> lst = new Vector<String>();
                lst.add(rsTreatment.getString(rsmdtrt.getColumnName(2)));
                mdlTbTreat.addRow(lst);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbDiseaseItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSearchTreatmentMedicine().setVisible(true);
            }
        });
    }
    private void SimpleButton()
    {
        try
        {
            for (UIManager.LookAndFeelInfo lnf : 
                UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(lnf.getName())) {
                UIManager.setLookAndFeel(lnf.getClassName());
                break;
                }
        }
        } catch (Exception e) { JOptionPane.showMessageDialog(null, "Helol"); }
        
    }
    private void ConfigControl()
    {
        cmbDisease.setBackground(Color.WHITE);
//        btnExit.setBackground(Color.red);
//        btnExit.setFocusPainted(false);
    }
//    private void DecoratedForm()
//    {
//        getRootPane().setBorder(BorderFactory.createLineBorder(new Color(153,209,255), 2));
//        getContentPane().setBackground(Color.WHITE);
//    }
    private void GetDisease()
    {
        String sql = "Select * from Disease";
        try
        {
            //st = con.createStatement();
            rs = con.createStatement().executeQuery(sql);
            while(rs.next())
            {
                cmbDisease.addItem(rs.getString("Name"));
            }
        }catch (Exception e)
        {
            e.printStackTrace();
        }
        
    }
    private void InitQuery()
    {
        sqlMed = "select Disease.Name,Medicine.Name as MedName \n" +
"from (Medicine inner join Medication on Medicine.[Medicine#]= Medication.[Medicine#]) inner join Disease on Medication.[Disease.ID]=Disease.ID\n" +
"where Disease.Name='"+cmbDisease.getSelectedItem().toString()+"'";
        sqlTreatment = "select Disease.Name,Treatment.Name as TreatName \n" +
"from (Treatment inner join TreatmentDisease on Treatment.[Treatment#]= TreatmentDisease.[Treatment#]) inner join Disease on TreatmentDisease.[Disease.ID]=Disease.ID\n" +
"where Disease.Name='"+cmbDisease.getSelectedItem()+"'";
    }
    private void SetupTable()
    {
        mdlTbMed = (DefaultTableModel) tbMedicine.getModel();
        mdlTbTreat = (DefaultTableModel) tbTreatment.getModel();
//        mdlTbMed.addColumn("Medicine");
//        mdlTbTreat.addColumn("Treatment");
        tbMedicine.getTableHeader().setFont(new Font("Segoe UI Light",Font.PLAIN,20));
        tbTreatment.getTableHeader().setFont(new Font("Segoe UI Light",Font.PLAIN,20));
        tbMedicine.setRowHeight(35);
        tbTreatment.setRowHeight(35);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDisease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JTable tbMedicine;
    private javax.swing.JTable tbTreatment;
    // End of variables declaration//GEN-END:variables
}
