/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hcms;

import java.awt.Color;
import java.awt.Font;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harry
 */
public class FrmSearchTreatmentMedicine extends javax.swing.JFrame {

    /**
     * Creates new form FrmSearchTreatmentMedicine
     */
    Connection con;
    ResultSet rs,rsMed, rsTreatment;
    String sqlMed, sqlTreatment;
    DefaultTableModel mdlTbMed;
    DefaultTableModel mdlTbTreat;
    public FrmSearchTreatmentMedicine() {
        try
        {
            Class.forName(ConnectToDatabase.JDBC_Driver);
            con = DriverManager.getConnection(ConnectToDatabase.JDBC_Url);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        setUndecorated(true);
        SimpleButton();
        initComponents();
        SetupTable();
        DecoratedForm();
        ConfigControl();
        GetDisease();
        setLocationRelativeTo(null);
        //SimpleButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTreatment = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMedicine = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbDisease = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbTreatment.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tbTreatment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbTreatment);

        tbMedicine.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tbMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbMedicine);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel1.setText("Treatment");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Disease");

        cmbDisease.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        cmbDisease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Disease" }));
        cmbDisease.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDiseaseItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Medicine");

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_30px.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbDisease, 0, 361, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(456, 456, 456))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(964, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(222, 222, 222)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(454, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbDiseaseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDiseaseItemStateChanged
        // TODO add your handling code here:
        mdlTbMed.setRowCount(0);
        mdlTbTreat.setRowCount(0);
        try {
            // TODO add your handling code here:
            ResultSetMetaData rsmdmed, rsmdtrt;
            InitQuery();
            rsMed = con.createStatement().executeQuery(sqlMed);
            rsTreatment = con.createStatement().executeQuery(sqlTreatment);
            rsmdmed = rsMed.getMetaData();
            rsmdtrt = rsTreatment.getMetaData();
            while(rsMed.next())
            {
                Vector<String> lst = new Vector<String>();
                lst.add(rsMed.getString(rsmdmed.getColumnName(2)));
                mdlTbMed.addRow(lst);
            }
            while(rsTreatment.next())
            {
                Vector<String> lst = new Vector<String>();
                lst.add(rsTreatment.getString(rsmdtrt.getColumnName(2)));
                mdlTbTreat.addRow(lst);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbDiseaseItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSearchTreatmentMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSearchTreatmentMedicine().setVisible(true);
            }
        });
    }
    private void SimpleButton()
    {
        try
        {
            for (UIManager.LookAndFeelInfo lnf : 
                UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(lnf.getName())) {
                UIManager.setLookAndFeel(lnf.getClassName());
                break;
                }
        }
        } catch (Exception e) { JOptionPane.showMessageDialog(null, "Helol"); }
        
    }
    private void ConfigControl()
    {
        cmbDisease.setBackground(Color.WHITE);
        btnExit.setBackground(Color.red);
        btnExit.setFocusPainted(false);
    }
    private void DecoratedForm()
    {
        getRootPane().setBorder(BorderFactory.createLineBorder(new Color(153,209,255), 2));
        getContentPane().setBackground(Color.WHITE);
    }
    private void GetDisease()
    {
        String sql = "Select * from Disease";
        try
        {
            //st = con.createStatement();
            rs = con.createStatement().executeQuery(sql);
            while(rs.next())
            {
                cmbDisease.addItem(rs.getString("Name"));
            }
        }catch (Exception e)
        {
            e.printStackTrace();
        }
        
    }
    private void InitQuery()
    {
        sqlMed = "select Disease.Name,Medicine.Name as MedName \n" +
"from (Medicine inner join Medication on Medicine.[Medicine#]= Medication.[Medicine#]) inner join Disease on Medication.[Disease.ID]=Disease.ID\n" +
"where Disease.Name='"+cmbDisease.getSelectedItem().toString()+"'";
        sqlTreatment = "select Disease.Name,Treatment.Name as TreatName \n" +
"from (Treatment inner join TreatmentDisease on Treatment.[Treatment#]= TreatmentDisease.[Treatment#]) inner join Disease on TreatmentDisease.[Disease.ID]=Disease.ID\n" +
"where Disease.Name='"+cmbDisease.getSelectedItem()+"'";
    }
    private void SetupTable()
    {
        mdlTbMed = (DefaultTableModel) tbMedicine.getModel();
        mdlTbTreat = (DefaultTableModel) tbTreatment.getModel();
        mdlTbMed.addColumn("Medicine");
        mdlTbTreat.addColumn("Treatment");
        tbMedicine.getTableHeader().setFont(new Font("Segoe UI Light",Font.PLAIN,20));
        tbTreatment.getTableHeader().setFont(new Font("Segoe UI Light",Font.PLAIN,20));
        tbMedicine.setRowHeight(35);
        tbTreatment.setRowHeight(35);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbDisease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbMedicine;
    private javax.swing.JTable tbTreatment;
    // End of variables declaration//GEN-END:variables
}
